#!/bin/sh

# Slackware build script
#Copyright (c) 2009, firebird619 <firebird209@gmail.com>
#
#Permission to use, copy, modify, and/or distribute this software for any
#purpose with or without fee is hereby granted, provided that the above
#copyright notice and this permission notice appear in all copies.
#
#THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF 
#MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.


PRGNAM=mixxx_
VERSION=1.6.1
ARCH=${ARCH:-i686}
BUILD=${BUILD:-1}
TAG=${TAG:-_SB}


# Set up build environment
CWD=$(pwd)
TMP=${TMP:-/tmp/SB}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i686" ] ; then
  SLKCFLAGS="-O2 -march=i686"
elif [ "$ARCH" = "i486" ] ; then
  SLKCFLAGS="-O2 -march=i486"
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM$VERSION+Herc.orig.tar.?z* || exit 1

cd mixxx-$VERSION+Herc

# Permissions
chown -R root:root .
find . \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 400 -o -perm 440 \) -exec chmod 644 {} \; -o \
 \( -perm 777 -o -perm 775 -o -perm 511 -o -perm 711 -o -perm 555 \) -exec chmod 755 {} \;


# Configure...
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
export QTDIR=/usr/lib/qt4/
scons prefix=/usr qtdir=/usr/lib/qt4/ || exit 1

# Install...
scons prefix=/usr qtdir=/usr/lib/qt4/ install || exit 1

# Prepare package

( cd $PKG
  if [ -d usr/man ]; then
    cd usr/man
    find -type f -exec gzip -9 {} \;
    for deadlink in $(find -type l ! -iname "*.gz"); do
      ln -s $(readlink $deadlink).gz $deadlink.gz
      rm $deadlink
    done
  fi

  if [ -d usr/info ] ; then
    rm -rf usr/info/dir
    gzip -9 usr/info/*
  fi

  find -type f | xargs file | grep ELF | cut -f1 -d: | xargs strip --strip-unneeded 2> /dev/null
)

if [ ! -d $PKG/usr/doc/$PRGNAM-$VERSION ] ; then
  mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
fi

cp -a COPYING LICENSE README \
  $PKG/usr/doc/$PRGNAM-$VERSION

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
if [ -f $CWD/doinst.sh ] ; then
  cat $CWD/doinst.sh > $PKG/install/doinst.sh
fi

# Make the package...
cd $PKG
makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz